### ISSUE TITLE
lazygitの反映速度UP

### ISSUE THREAD

**Issue by yyossy5** [yyossy5/dotfiles#261]

**Comment by yyossy5** [comment]
https://github.com/tonyvitonis/lazygit/blob/master/docs/Config.md

を見る感じ以下の設定が関係ありそう

```yml
# Background refreshes
refresher:
  # File/submodule refresh interval in seconds.
  # Auto-refresh can be disabled via option 'git.autoRefresh'.
  refreshInterval: 10

  # Re-fetch interval in seconds.
  # Auto-fetch can be disabled via option 'git.autoFetch'.
  fetchInterval: 60
```

試してみた感じ、ブランチ変更の反映速度に関係あるのはfetchIntervalのほう
